### ISSUE TITLE
Creating a logo for react-daraja

### ISSUE THREAD

**Issue by abubakar508** [amosmachora/react-daraja#38]
We need a logo for react-daraja. I can help with that.

**Comment by amosmachora** [comment]
okay. I actually agree I was just too lazy to come up with one. You can create one and if you can update the docs and readme to include the new logo the open source community will be grateful.

**Comment by amosmachora** [comment]
hey @abubakar508 how is the logo coming

**Comment by abubakar508** [comment]
By tomorrow

**Comment by amosmachora** [comment]
okay thanks. waiting

**Comment by abubakar508** [comment]
Text me in whatsapp via +254720831147

**Comment by amosmachora** [comment]
Im going to close this now. @abubakar508 thanks.
